name: 每日获取节点

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  daily-checkin:
    runs-on: ubuntu-latest

    steps:
    - name: Set up date variables
      run: |
        CURRENT_DATE=$(date +%Y-%m-%d)
        YYYY=$(date +%Y)
        M=$(date +%-m)  # 获取当前月份，去掉前导零
        YYYYMMDD=$(date +%Y%m%d)
        echo "Current date: $CURRENT_DATE"
        echo "Constructed URL: https://a.nodeshare.xyz/uploads/$YYYY/$M/$YYYYMMDD"
        echo "url=https://a.nodeshare.xyz/uploads/$YYYY/$M/$YYYYMMDD" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v4

    - id: check_file
      name: Check if files exist
      run: |
        echo "Starting file check with URL: ${{ env.url }}"
        FILE_EXTENSIONS=("json" "yaml" "txt")
        EXISTING_FILES=""
        for ext in "${FILE_EXTENSIONS[@]}"; do
          FILE_URL="${{ env.url }}.$ext"
          echo "Checking $FILE_URL"
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null "$FILE_URL")
          echo "HTTP Response: $RESPONSE"
          if [ "$RESPONSE" -eq 200 ]; then
            echo "File exists: $FILE_URL"
            EXISTING_FILES="$EXISTING_FILES $ext"
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "File not found: $FILE_URL"
          fi
        done
        if [ -z "$EXISTING_FILES" ]; then
          echo "No files exist."
          echo "file_exists=false" >> $GITHUB_OUTPUT
        else
          echo "existing_files=$EXISTING_FILES" >> $GITHUB_OUTPUT
        fi

    - name: Create ssr directory
      if: steps.check_file.outputs.file_exists == 'true'
      run: |
        mkdir -p ssr

    - name: Download files
      if: steps.check_file.outputs.file_exists == 'true'
      run: |
        mkdir -p ssr
        for ext in ${{ steps.check_file.outputs.existing_files }}; do
          FILE_URL="${{ env.url }}.$ext"
          OUTPUT_FILE="ssr/node_ssr.$ext"
          curl -o "$OUTPUT_FILE" "$FILE_URL"
          echo "Downloaded: $OUTPUT_FILE"
        done
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add ssr/
        git commit -m "Add nodeshare files to ssr directory for $(date +%Y%m%d)"
        git push
