name: 每日更新ssr订阅

on:
  schedule:
    - cron: '0 12 * * *'  # 每天中午12点执行

jobs:
  check_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up date variables
        id: vars
        run: |
          CURRENT_DATE=$(date +%Y-%m-%d)
          YYYY=$(date +%Y)
          M=$(date +%-m)
          YYYYMMDD=$(date +%Y%m%d)
          echo "Current date: $CURRENT_DATE"
          echo "YYYY=$YYYY" >> $GITHUB_ENV
          echo "M=$M" >> $GITHUB_ENV
          echo "YYYYMMDD=$YYYYMMDD" >> $GITHUB_ENV

      - name: Construct URL
        id: construct_url
        run: |
          URL="https://a.nodeshare.xyz/uploads/${{ env.YYYY }}/${{ env.M }}/${{ env.YYYYMMDD }}.json"
          echo "url=$URL" >> $GITHUB_ENV

      - name: Check if JSON file exists
        id: check_file
        run: |
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null "${{ env.url }}")
          echo "HTTP Response: $RESPONSE"
          if [ "$RESPONSE" -eq 200 ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Download and save JSON file
        if: steps.check_file.outputs.file_exists == 'true'
        run: |
          FILENAME="node_ssr.json"
          curl -o "$FILENAME" "${{ env.url }}"
          
      - name: Commit and push changes
        if: steps.check_file.outputs.file_exists == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add "$FILENAME"
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update JSON file from nodeshare for ${{ env.YYYYMMDD }}"
            git push
          fi
